import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  tr: {
    home: "Ana Sayfa",
    movies: "Filmler",
    series: "Diziler",
    curator_rooms: "Küratör Odaları",
    admin_panel: "Admin Paneli",
    profile_change: "Profil Değiştir",
    logout: "Çıkış Yap",
    search_placeholder: "Film, dizi, oyuncu veya tür ara...",
    weekly_top10: "Haftalık En Popüler TOP 10",
    curator_lists: "Kullanıcı Küratör Listeleri",
    curator_badge: "Küratör Sensin",
    curator_selections: "GÜNÜN KINOIA SEÇİMİ",
    examine_and_play: "İncele & Oynat",
    continue_watching: "İzlemeye Devam Et",
    remaining: "Kalan",
    room_inspect: "Odayı İncele",
    close: "Kapat",
    new_added: "Yeni Eklenenler",
    who_is_watching: "KINOIA'yı Kim İzliyor?",
    profile_add: "Profil Ekle",
    profile_name: "Profil Adı",
    create: "Oluştur",
    role: "Rol",
    mock_switch: "Mock Rol/Abone Değiştir",
    active_subscriber: "Aktif Abone",
    inactive_member: "Pasif Üye",
    curator_review: "Küratör İncelemesi",
    director: "Yönetmen",
    cast: "Oyuncular",
    watch_now: "Şimdi İzle",
    seasons: "Sezonlar",
    episodes: "Bölümler",
    similar_recommendations: "Bu İçeriği Sevenler Bunları Da İzledi",
    no_content_found: "Kriterlere uygun film bulunamadı.",
    no_movies_added: "Henüz film eklenmedi.",
    no_series_added: "Henüz dizi eklenmedi.",
    empty_watchlist: "Küratör odanız şu anda boş. Keşfetmek için içeriklerin detay sayfasından odanıza ekleyebilirsiniz.",
    curator_rooms_title: "Küratör Odalarım",
    add_to_curator_room: "Küratör Odama Ekle",
    add_to_watchlist: "İzleme Listeme Ekle",
    new_room_form: "Yeni Oda Oluştur & Ekle",
    room_title_placeholder: "Oda Başlığı (Örn: Cuma Gecesi)",
    room_desc_placeholder: "Açıklama (Opsiyonel)",
    create_and_add: "Oluştur ve Ekle",
    no_room_created: "Henüz küratör listesi oluşturmadınız.",
    added_to_room: "Küratör odasına eklendi!",
    removed_from_room: "Küratör odasından kaldırıldı!",
    created_and_added: "Yeni liste oluşturuldu ve film eklendi! 🎬",
    language_select: "Dil Seçimi",
    language_filter: "Dil Filtresi",
    all: "Tümü",
    turkish: "Türkçe",
    english: "İngilizce",
    russian: "Rusça",
    german: "Almanca",
    french: "Fransızca",
    day_selection: "GÜNÜN SİNEMATİK SEÇİMİ",
    weekly_recom: "HAFTALIK ÖNERİ",
    play_now: "Şimdi İzle",
    more_info: "Daha Fazla Bilgi",
    interactive_xray: "X-RAY İNTERAKTİF",
    in_scene: "Sahnede Olanlar",
    scene_song: "Sahne Müziği",
    unknown_cast: "Bilinmeyen Oyuncu",
    kinoia_music: "Kinoia Orijinal Müziği",
    report_issue: "Sorun Bildir",
    firewall: "KINOIA MAX GÜVENLİK DUVARI",
    maintenance_title: "İçerik Şu An Bakımda",
    maintenance_desc: "İstediğiniz video kaynağına şu an erişilemiyor veya kırık link algılandı. Teknik sinema küratörlerimiz sorunu çözmek için bakım çalışmalarına başladı.",
    try_again: "Tekrar Dene",
    back_btn: "Geri Dön",
    now_playing: "Şu An Oynatılan Bölüm",
    close_player: "Oynatıcıyı Kapat",
    director_label: "Yönetmen",
    actors_label: "Oyuncular",
    admin_stats: "Sistem İstatistikleri",
    total_content: "Toplam İçerik",
    total_members: "Toplam Üye",
    active_members: "Aktif Abone",
    content_list: "Kütüphane Listesi",
    add_new_content: "Yeni İçerik Ekle",
    series_only: "Sadece Dizi",
    movie_only: "Sadece Film",
    edit: "Düzenle",
    delete: "Sil",
    save_content: "İçeriği Kaydet",
    trailer_only: "Sadece Fragman",
    seasons_count: "Sezon Sayısı",
    weekly_recom_label: "Haftalık Önerilen",
    origin_label: "Köken (hollywood/turkish/other)",
    unauthorized_desc: "Bu içeriği izleyebilmek için aktif bir aboneliğinizin olması gerekmektedir."
  },
  en: {
    home: "Home",
    movies: "Movies",
    series: "TV Shows",
    curator_rooms: "Curator Rooms",
    admin_panel: "Admin Panel",
    profile_change: "Switch Profile",
    logout: "Log Out",
    search_placeholder: "Search movie, TV show, cast or genre...",
    weekly_top10: "Weekly Most Popular TOP 10",
    curator_lists: "User Curator Playlists",
    curator_badge: "You Are The Curator",
    curator_selections: "KINOIA SELECTION OF THE DAY",
    examine_and_play: "Inspect & Play",
    continue_watching: "Continue Watching",
    remaining: "Remaining",
    room_inspect: "Inspect Room",
    close: "Close",
    new_added: "Newly Added",
    who_is_watching: "Who is Watching KINOIA?",
    profile_add: "Add Profile",
    profile_name: "Profile Name",
    create: "Create",
    role: "Role",
    mock_switch: "Switch Mock Role/Sub",
    active_subscriber: "Active Subscriber",
    inactive_member: "Inactive Member",
    curator_review: "Curator Review",
    director: "Director",
    cast: "Cast",
    watch_now: "Watch Now",
    seasons: "Seasons",
    episodes: "Episodes",
    similar_recommendations: "People Who Liked This Also Watched",
    no_content_found: "No content found matching criteria.",
    no_movies_added: "No movies added yet.",
    no_series_added: "No TV shows added yet.",
    empty_watchlist: "Your curator room is currently empty. You can add titles from their detail page.",
    curator_rooms_title: "My Curator Rooms",
    add_to_curator_room: "Add to Curator Room",
    add_to_watchlist: "Add to Watchlist",
    new_room_form: "Create New Room & Add",
    room_title_placeholder: "Room Title (e.g. Friday Night)",
    room_desc_placeholder: "Description (Optional)",
    create_and_add: "Create and Add",
    no_room_created: "You haven't created a curator room yet.",
    added_to_room: "Added to curator room!",
    removed_from_room: "Removed from curator room!",
    created_and_added: "New room created and movie added! 🎬",
    language_select: "Language Selection",
    language_filter: "Language Filter",
    all: "All",
    turkish: "Turkish",
    english: "English",
    russian: "Russian",
    german: "German",
    french: "French",
    day_selection: "CINEMATIC SELECTION OF THE DAY",
    weekly_recom: "WEEKLY RECOMMENDATION",
    play_now: "Play Now",
    more_info: "More Information",
    interactive_xray: "X-RAY INTERACTIVE",
    in_scene: "In Scene",
    scene_song: "Scene Soundtrack",
    unknown_cast: "Unknown Actor",
    kinoia_music: "Kinoia Original Track",
    report_issue: "Report Issue",
    firewall: "KINOIA MAX SECURITY FIREWALL",
    maintenance_title: "Content Under Maintenance",
    maintenance_desc: "The requested video source is currently unreachable or a broken link was detected. Our cinematic curators are on it.",
    try_again: "Try Again",
    back_btn: "Go Back",
    now_playing: "Currently Playing",
    close_player: "Close Player",
    director_label: "Director",
    actors_label: "Actors",
    admin_stats: "System Statistics",
    total_content: "Total Content",
    total_members: "Total Members",
    active_members: "Active Subs",
    content_list: "Library Index",
    add_new_content: "Add New Title",
    series_only: "TV Show Only",
    movie_only: "Movie Only",
    edit: "Edit",
    delete: "Delete",
    save_content: "Save Title Details",
    trailer_only: "Trailer Only",
    seasons_count: "Seasons Count",
    weekly_recom_label: "Weekly Recommended",
    origin_label: "Origin (hollywood/turkish/other)",
    unauthorized_desc: "You need an active subscription to stream this content."
  },
  ru: {
    home: "Главная",
    movies: "Фильмы",
    series: "Сериалы",
    curator_rooms: "Кураторские Комнаты",
    admin_panel: "Панель Админа",
    profile_change: "Сменить Профиль",
    logout: "Выйти",
    search_placeholder: "Поиск фильмов, сериалов, актеров...",
    weekly_top10: "Еженедельный ТОП-10 популярного",
    curator_lists: "Пользовательские Комнаты Куратора",
    curator_badge: "Вы Куратор",
    curator_selections: "ВЫБОР КУРАТОРА KINOIA НА СЕГОДНЯ",
    examine_and_play: "Смотреть & Играть",
    continue_watching: "Продолжить просмотр",
    remaining: "Осталось",
    room_inspect: "Осмотреть комнату",
    close: "Закрыть",
    new_added: "Новинки",
    who_is_watching: "Кто смотрит KINOIA?",
    profile_add: "Добавить профиль",
    profile_name: "Имя профиля",
    create: "Создать",
    role: "Роль",
    mock_switch: "Переключить подписку/роль",
    active_subscriber: "Активный подписчик",
    inactive_member: "Неактивный член",
    curator_review: "Рецензия куратора",
    director: "Режиссер",
    cast: "В ролях",
    watch_now: "Смотреть сейчас",
    seasons: "Сезоны",
    episodes: "Эпизоды",
    similar_recommendations: "Люди, которым это понравилось, также смотрели",
    no_content_found: "Контент не найден.",
    no_movies_added: "Фильмы пока не добавлены.",
    no_series_added: "Сериалы пока не добавлены.",
    empty_watchlist: "Ваша комната куратора пуста. Вы можете добавить фильмы со страницы описания.",
    curator_rooms_title: "Мои комнаты куратора",
    add_to_curator_room: "Добавить в комнату куратора",
    add_to_watchlist: "Добавить в список наблюдения",
    new_room_form: "Создать новую комнату и добавить",
    room_title_placeholder: "Название комнаты (например, Пятничный вечер)",
    room_desc_placeholder: "Описание (необязательно)",
    create_and_add: "Создать и добавить",
    no_room_created: "Вы еще не создали комнату куратора.",
    added_to_room: "Добавлено в комнату куратора!",
    removed_from_room: "Удалено из комнаты куратора!",
    created_and_added: "Новая комната создана, фильм добавлен! 🎬",
    language_select: "Выбор Языка",
    language_filter: "Фильтр Языка",
    all: "Все",
    turkish: "Турецкий",
    english: "Английский",
    russian: "Русский",
    german: "Немецкий",
    french: "Французский",
    day_selection: "СИНЕМАТИЧЕСКИЙ ВЫБОР ДНЯ",
    weekly_recom: "ЕЖЕНЕДЕЛЬНАЯ РЕКОМЕНДАЦИЯ",
    play_now: "Смотреть сейчас",
    more_info: "Подробнее",
    interactive_xray: "X-RAY ИНТЕРАКТИВ",
    in_scene: "В этой сцене",
    scene_song: "Саундтрек к сцене",
    unknown_cast: "Неизвестный актер",
    kinoia_music: "Оригинальный трек Kinoia",
    report_issue: "Сообщить о проблеме",
    firewall: "БРАНДМАУЭР БЕЗОПАСНОСТИ KINOIA MAX",
    maintenance_title: "Контент на обслуживании",
    maintenance_desc: "Запрошенный видеоисточник в настоящее время недоступен. Наши кинематографические кураторы уже занимаются этим.",
    try_again: "Повторить попытку",
    back_btn: "Назад",
    now_playing: "Сейчас играет",
    close_player: "Закрыть плеер",
    director_label: "Режиссер",
    actors_label: "Актеры",
    admin_stats: "Статистика Системы",
    total_content: "Всего контента",
    total_members: "Всего членов",
    active_members: "Активные суб",
    content_list: "Индекс библиотеки",
    add_new_content: "Добавить новый заголовок",
    series_only: "Только сериалы",
    movie_only: "Только фильмы",
    edit: "Редактировать",
    delete: "Удалить",
    save_content: "Сохранить данные",
    trailer_only: "Только трейлер",
    seasons_count: "Количество сезонов",
    weekly_recom_label: "Рекомендовано еженедельно",
    origin_label: "Происхождение (hollywood/turkish/other)",
    unauthorized_desc: "Вам нужна активная подписка для потоковой передачи этого контента."
  },
  de: {
    home: "Startseite",
    movies: "Filme",
    series: "Serien",
    curator_rooms: "Kuratorenräume",
    admin_panel: "Admin-Bereich",
    profile_change: "Profil wechseln",
    logout: "Abmelden",
    search_placeholder: "Filme, Serien, Besetzung oder Genre suchen...",
    weekly_top10: "Wöchentliche TOP 10 Beliebt",
    curator_lists: "Kuratoren-Playlists der Nutzer",
    curator_badge: "Du bist der Kurator",
    curator_selections: "KINOIA WAHL DES TAGES",
    examine_and_play: "Ansehen & Abspielen",
    continue_watching: "Weiterschauen",
    remaining: "Verbleibend",
    room_inspect: "Raum inspizieren",
    close: "Schließen",
    new_added: "Neu Hinzugefügt",
    who_is_watching: "Wer schaut KINOIA?",
    profile_add: "Profil hinzufügen",
    profile_name: "Profilname",
    create: "Erstellen",
    role: "Rolle",
    mock_switch: "Mock-Rolle/Abo umschalten",
    active_subscriber: "Aktiver Abonnent",
    inactive_member: "Inaktives Mitglied",
    curator_review: "Kuratoren-Rezension",
    director: "Regisseur",
    cast: "Besetzung",
    watch_now: "Jetzt Anschauen",
    seasons: "Staffeln",
    episodes: "Episoden",
    similar_recommendations: "Kunden, die dies kauften, sahen auch",
    no_content_found: "Keine passenden Inhalte gefunden.",
    no_movies_added: "Noch keine Filme hinzugefügt.",
    no_series_added: "Noch keine Serien hinzugefügt.",
    empty_watchlist: "Dein Kuratorenraum ist leer. Du kannst Titel auf der Detailseite hinzufügen.",
    curator_rooms_title: "Meine Kuratorenräume",
    add_to_curator_room: "Zum Kuratorenraum hinzufügen",
    add_to_watchlist: "Auf die Merkliste",
    new_room_form: "Neuen Raum erstellen & hinzufügen",
    room_title_placeholder: "Raumtitel (z. B. Freitagnacht)",
    room_desc_placeholder: "Beschreibung (Optional)",
    create_and_add: "Erstellen und hinzufügen",
    no_room_created: "Du hast noch keinen Kuratorenraum erstellt.",
    added_to_room: "Zum Kuratorenraum hinzugefügt!",
    removed_from_room: "Aus dem Kuratorenraum entfernt!",
    created_and_added: "Neuer Raum erstellt und Film hinzugefügt! 🎬",
    language_select: "Sprachauswahl",
    language_filter: "Sprachfilter",
    all: "Alle",
    turkish: "Deutsch", // "Deutsch" mapped dynamically
    english: "Englisch",
    russian: "Russisch",
    german: "Deutsch",
    french: "Französisch",
    day_selection: "FILM-HIGHLIGHT DES TAGES",
    weekly_recom: "WÖCHENTLICHE EMPFEHLUNG",
    play_now: "Jetzt ansehen",
    more_info: "Mehr Infos",
    interactive_xray: "X-RAY INTERAKTIV",
    in_scene: "In der Szene",
    scene_song: "Szene-Soundtrack",
    unknown_cast: "Unbekannter Schauspieler",
    kinoia_music: "Kinoia Original Track",
    report_issue: "Problem melden",
    firewall: "KINOIA MAX SICHERHEITS-FIREWALL",
    maintenance_title: "Inhalt wird gewartet",
    maintenance_desc: "Die angeforderte Videoquelle ist derzeit nicht erreichbar. Unsere kinematografischen Kuratoren sind dran.",
    try_again: "Erneut versuchen",
    back_btn: "Zurück",
    now_playing: "Aktuelle Wiedergabe",
    close_player: "Player schließen",
    director_label: "Regisseur",
    actors_label: "Besetzung",
    admin_stats: "System-Statistiken",
    total_content: "Inhalte Gesamt",
    total_members: "Mitglieder Gesamt",
    active_members: "Aktive Abos",
    content_list: "Bibliotheksindex",
    add_new_content: "Neuen Titel hinzufügen",
    series_only: "Nur Serien",
    movie_only: "Nur Filme",
    edit: "Bearbeiten",
    delete: "Löschen",
    save_content: "Details speichern",
    trailer_only: "Nur Trailer",
    seasons_count: "Anzahl Staffeln",
    weekly_recom_label: "Wöchentlich empfohlen",
    origin_label: "Herkunft (hollywood/turkish/other)",
    unauthorized_desc: "Sie benötigen ein aktives Abonnement, um diesen Inhalt zu streamen."
  },
  fr: {
    home: "Accueil",
    movies: "Films",
    series: "Séries",
    curator_rooms: "Salles de Conservation",
    admin_panel: "Panneau d'administration",
    profile_change: "Changer de Profil",
    logout: "Se déconnecter",
    search_placeholder: "Rechercher un film, une série, un acteur...",
    weekly_top10: "TOP 10 hebdomadaire populaire",
    curator_lists: "Playlists des Conservateurs",
    curator_badge: "Vous Êtes le Conservateur",
    curator_selections: "SÉLECTION DU JOUR KINOIA",
    examine_and_play: "Inspecter & Jouer",
    continue_watching: "Reprendre la lecture",
    remaining: "Restant",
    room_inspect: "Inspecter la salle",
    close: "Fermer",
    new_added: "Récemment Ajoutés",
    who_is_watching: "Qui regarde KINOIA ?",
    profile_add: "Ajouter un profil",
    profile_name: "Nom du profil",
    create: "Créer",
    role: "Rôle",
    mock_switch: "Basculer rôle/abonnement mock",
    active_subscriber: "Abonné Actif",
    inactive_member: "Membre Inactif",
    curator_review: "Avis du conservateur",
    director: "Réalisateur",
    cast: "Acteurs",
    watch_now: "Regarder maintenant",
    seasons: "Saisons",
    episodes: "Épisodes",
    similar_recommendations: "Les utilisateurs ont également regardé",
    no_content_found: "Aucun contenu trouvé.",
    no_movies_added: "Aucun film ajouté pour le moment.",
    no_series_added: "Aucune série ajoutée pour le moment.",
    empty_watchlist: "Votre salle de conservation est vide. Ajoutez des titres depuis la page de détails.",
    curator_rooms_title: "Mes salles de conservation",
    add_to_curator_room: "Ajouter à la salle de conservation",
    add_to_watchlist: "Ajouter à ma liste",
    new_room_form: "Créer une nouvelle salle & ajouter",
    room_title_placeholder: "Titre de la salle (ex. Vendredi soir)",
    room_desc_placeholder: "Description (Optionnel)",
    create_and_add: "Créer et ajouter",
    no_room_created: "Vous n'avez pas encore créé de salle de conservation.",
    added_to_room: "Ajouté à la salle de conservation !",
    removed_from_room: "Retiré de la salle de conservation !",
    created_and_added: "Nouvelle salle créée et film ajouté ! 🎬",
    language_select: "Choix de la Langue",
    language_filter: "Filtre de Langue",
    all: "Tout",
    turkish: "Turc",
    english: "Anglais",
    russian: "Russe",
    german: "Allemand",
    french: "Français",
    day_selection: "SÉLECTION CINÉMATIQUE DU JOUR",
    weekly_recom: "RECOMMANDATION HEBDOMADAIRE",
    play_now: "Regarder maintenant",
    more_info: "Plus d'infos",
    interactive_xray: "X-RAY INTERACTIF",
    in_scene: "Dans cette scène",
    scene_song: "Bande originale",
    unknown_cast: "Acteur inconnu",
    kinoia_music: "Kinoia Original Track",
    report_issue: "Signaler un problème",
    firewall: "PARE-FEU DE SÉCURITÉ KINOIA MAX",
    maintenance_title: "Contenu en maintenance",
    maintenance_desc: "La source vidéo demandée est actuellement inaccessible. Nos conservateurs sont sur le coup.",
    try_again: "Réessayer",
    back_btn: "Retour",
    now_playing: "Actuellement en lecture",
    close_player: "Fermer le lecteur",
    director_label: "Réalisateur",
    actors_label: "Acteurs",
    admin_stats: "Statistiques du Système",
    total_content: "Contenu Total",
    total_members: "Membres Totaux",
    active_members: "Abonnés Actifs",
    content_list: "Index de la bibliothèque",
    add_new_content: "Ajouter un titre",
    series_only: "Série uniquement",
    movie_only: "Film uniquement",
    edit: "Modifier",
    delete: "Supprimer",
    save_content: "Enregistrer les détails",
    trailer_only: "Bande-annonce uniquement",
    seasons_count: "Nombre de saisons",
    weekly_recom_label: "Recommandé chaque semaine",
    origin_label: "Origine (hollywood/turkish/other)",
    unauthorized_desc: "Vous devez avoir un abonnement actif pour lire ce contenu."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(localStorage.getItem('lang') || 'tr');

  const setLanguage = (lang) => {
    localStorage.setItem('lang', lang);
    setLanguageState(lang);
  };

  const t = (key) => {
    const langDict = translations[language] || translations['tr'];
    return langDict[key] || translations['tr'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
